[book]
title = "Rhai - Embedded Scripting for Rust"
authors = ["Jonathan Turner", "Stephen Chung"]
description = "Tutorial and reference on the Rhai scripting engine and language."
language = "en"

[output.html]
no-section-label = true
additional-css = [ "stylesheets/rhai.min.css" ]
git-repository-url = "https://github.com/rhaiscript/rhai"
edit-url-template = "https://github.com/rhaiscript/book/edit/master/{path}"
curly-quotes = true
google-analytics = "UA-195121118-1"

[output.html.fold]
enable = true
level = 4

[outputX.linkcheck]
follow-web-links = false
traverse-parent-directories = false
warning-policy = "ignore"

[preprocessor.tera]
command = "mdbook-tera --json ./src/context.json"
